/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Total Boosted Factories boost fuel gain": "总计提升的工厂 提升燃料增益",
    "Total factories boost Golden Scrap gain": "工厂总数提高了金废料的增益",
    "Total scrap factories boost Golden Scrap gain": "废钢工厂总数提高了金废钢的收益",
    "Total Scrap factories boost Golden Scrap gain": "废钢工厂总数提高了金废钢的收益",
    "Total Scrap Factories boost Magnet and Steel Beam gain": "总计废料工厂 提升磁铁和钢梁增益",
    "Total scrap factories boost Scrap and Golden Scrap gain": "废钢工厂总数提高废钢和金废钢的收益",
    "Total scrap factories boost Scrap gain": "废钢厂总数提高废钢收益",
    "Total Super Factories boost 16th GS Upgrade effect": "超级工厂总数提升第 16 次 GS 升级效果",
    "Total Super Factories boost 3rd NMU effect": "超级工厂总数提升了第三个 NMU 效应",
    "Total Super factories boost extra scrap factory gain": "超级工厂总数增加了额外的废品工厂收益",
    "Total Super Factories boost extra scrap factory gain": "超级工厂总数增加了额外的废品工厂收益",
    "Total Super factories boost Golden Scrap gain": "超级工厂总数提高了金废料的收益",
    "Total Super Factories boost Prestige Gain": "超级工厂总数提升声望增益",
    "Total Super factories generate extra levels of 2nd RMU": "超级工厂总数产生额外级别的第二个 RMU",
    "Unlock Booster Challenges": "解锁助推器挑战",
    "Unlock Boosters (Prestige layer)": "解锁助推器（声望层）",
    "Unlock Bricks": "解锁砖块",
    "Unlock Decayverse": "解锁衰变宇宙",
    "Unlock Empowerment (Prestige Layer)(Coming Soon)": "解锁赋能（威望层）（即将推出）",
    "Unlock Magnets": "解锁磁铁",
    "Unlock super factories and prestiging now subtracts": "解锁超级工厂和声望现在减去",
    "Upgrade Auto-Multiplicator": "升级自动乘法器",
    "Upgrade Autoclicker": "升级自动点击器",
    "Upgrades": "升级",
    "Walkthrough Video": "演练视频",
    "Welcome!": "欢迎！",
    "where p is": "其中 p 是",
    "wrenches": "扳手",
    "Wrenches make all RBU costs cheaper": "扳手使所有 RBU 成本更便宜",
    "RBU Autobuyer:": "RBU 自动购买者：",
    "Regeneration Points (+": "再生点 (+",
    "Regenerators and Regeneration Points.": "再生器和再生点。",
    "Regenerators provide more RP base gain and regenerator gain is boosted by its amount": "再生器提供更多的 RP 基础增益，并且再生器增益由其数量提升",
    "regenerators, which have provided you a base RP gain of +": "再生器，它们为您提供了 + 的基础 RP 增益",
    "Reinhardt's True Infinity γ": "莱因哈特的真无穷 γ",
    "Removed": "已移除",
    "Removed some news tickers.": "删除了一些新闻代码。",
    "Repeatable Brick Upgrades (RBU)": "可重复块升级 (RBU)",
    "Repeatable Magnet Upgrades (RMU)": "可重复磁铁升级 (RMU)",
    "Reset your fuel upgrades": "重置您的燃料升级",
    "Reward: +": "奖励：+",
    "Reward: 2nd RBU levels boost prestige gain by": "奖励：第 2 个 RBU 等级提升声望增益",
    "Reward: Boost 22nd Golden Scrap Upgrade effect by": "奖励：提升第 22 次金废料升级效果",
    "Reward: Prestiges boost 11th GS Upgrade effect by": "奖励：声望提升 11 次 GS 升级效果",
    "Reward: Raise your 1st RMU Effect to": "奖励：将您的第一个 RMU 效果提升到",
    "Reward: Star effect is raised to": "奖励：星级效果提升至",
    "Reward: Total boosted factories boost Booster gain by": "奖励：总助推器的工厂将助推器增益提高",
    "Reward: Total Boosted Factories boost extra Super Factory gain by": "奖励：总加速工厂将额外的超级工厂增益提高",
    "Rewards do not apply when you have below 1 completion": "当您完成以下 1 次时，奖励不适用",
    "RP and gained wrenches boost each other": "RP 和增益扳手相互促进",
    "RP base gain: ^1.00 → ^1.25": "RP 基础增益：^1.00 → ^1.25",
    "Sacrifice all your bricks": "牺牲你所有的砖头",
    "Sacrifice all your magnets": "牺牲你所有的磁铁",
    "Sacrifice all your steel beams": "牺牲你所有的钢梁",
    "Saving Milestones": "保存里程碑",
    "Scaling Weakness (SW):": "缩放弱点（SW）：",
    "Scientific": "科学的",
    "Scrap boost per achievement is increased from 1.30x to 2.00x.": "每个成就的废料提升从 1.30 倍增加到 2.00 倍。",
    "Scrap Clicker++": "废料点击器++",
    "Synergizers.": "协同作用",
    "Synergy II Points (+": "协同作用 II 点 (+",
    "Synergy Points (+": "协同点数（+",
    "There is exponential super decay that divides all your pre-boosters resource amount and gain, and your scrap gain is divided by": "有一个指数级的超级衰减将你所有的前助推器资源量和收益除以，你的废品收益除以",
    "Thermal Energy": "热能",
    "Thermal Energy (+": "热能（+",
    "Thermal Energy boost its gain": "热能提高其收益",
    "Thermal Energy boost SW of Boosted Factory": "Boosted Factory的热能boost SW",
    "Thermal Energy effects use better formula": "热能效应使用更好的公式",
    "Thermal Energy make you to gain wrenches on sacrifice every second": "热能让你每秒钟都在牺牲中获得扳手",
    "Thermal Energy power up Golden Scrap effect": "热能提升金废料效果",
    "They are dividing all pre-boosters costs (including Scrap Factory and Super Factory cost) by": "他们将所有前置助推器成本（包括废品工厂和超级工厂成本）除以",
    "They are increasing your multiplicator base by": "他们正在通过以下方式增加您的乘数基数",
    "They are making your GS Slowdown start at": "他们让你的 GS 减速开始于",
    "They are making your multiplicators start to broken at": "他们让你的乘法器开始在",
    "They are multiplying all pre-boosters resources by": "他们将所有预助推器资源乘以",
    "They are multiplying your scrap gain by": "他们将您的废料收益乘以",
    "They are raising discounter point effect to the power of p": "他们将折扣点效应提高到 p 的幂",
    "This cannot be undone!": "这不能被撤消！",
    "this challenge": "这个挑战",
    "Generate prestiges based on golden scraps": "根据黄金碎片产生声望",
    "Golden scrap effect uses better formula": "金边效果使用更好的配方",
    "Golden Scrap effect uses better formula": "黄金废料效果使用更好的配方",
    "Golden Scraps": "黄金废料",
    "Golden Scraps and GS Upgrades,": "黄金废料和 GS 升级，",
    "Golden scraps boost 3rd NMU Effect": "金色废料提升第三个 NMU 效果",
    "Golden Scraps make wrench effect to brick self boost strength stronger": "黄金碎块使扳手效果对砖的自增强度更强",
    "golden scraps.": "金色的碎片。",
    "Golden Scraps.": "黄金碎片。",
    "green-bordered box": "绿框",
    "GS effect is raised to": "GS效果提升至",
    "GS Slowdown starts at": "GS减速开始于",
    "GS Upgrade Autobuyer:": "GS 升级自动购买者：",
    "Hard Reset": "硬重置",
    "Helpers:": "帮手：",
    "Hevipelle's Antimatter Dimensions": "Hevipelle 的反物质维度",
    "Hold on!!": "坚持，稍等！！",
    "Hover over every factory name to see the cost scaling weakness info": "将鼠标悬停在每个工厂名称上以查看成本扩展弱点信息",
    "Hover over the achievements to see details": "将鼠标悬停在成就上以查看详细信息",
    "How does antivirus work?": "防病毒软件如何工作？",
    "https://www.youtube.com/watch?v=HpTKBHYDQm6": "https://www.youtube.com/watch?v=HpTKBHYDQm6",
    "I bet you can't watch this video →": "我打赌你不能看这个视频 →",
    "Improved the saving system": "改进了储蓄系统",
    "in No Booster Challenge": "在无助推器挑战中",
    "In return, you will get Boosters": "作为回报，您将获得助推器",
    "In return, you will get Golden Scraps": "作为回报，您将获得黄金碎片",
    "Inflation point effect use better formula": "通货膨胀点效应使用更好的公式",
    "Inflation Points (+": "通货膨胀点 (+",
    "Inflators": "充气机",
    "Inflators.": "充气机。",
    "Insipiration:": "启示：",
    "Level:": "等级：",
    "LOCKED": "锁定",
    "Magnet, Steel Beam and Wrench gain are reduced a lot, Multiplicators start to broken instantly, but GS effect is raised to 2 and your scrap gain is divided by": "磁铁，钢梁和扳手增益减少很多，乘法器立即开始损坏，但GS效果提高到2并且您的废料增益除以",
    "Magnets": "磁铁",
    "Magnets and Protons": "磁铁和质子",
    "Magnets and Steel Beams": "磁铁和钢梁",
    "Magnets and Steel Beams boost each other": "磁铁和钢梁相互促进",
    "Magnets, Steel Beams, Protons and Electrons,": "磁铁、钢梁、质子和电子，",
    "Manual scrap clicks boost scrap gain": "手动报废点击提高报废收益",
    "manual scrap clicks.": "手动报废点击。",
    "Max All (M)": "最大全部 (M)",
    "Max All RBUs": "最大所有 RBU",
    "Max All RMUs": "最大所有 RMU",
    "Multiplying your Magnet gain by": "将您的磁铁增益乘以",
    "multiplying your Scrap gain by": "将您的废料收益乘以",
    "Multiplying your scrap gain by": "将您的废料收益乘以",
    "Multiplying your Steel Beam gain by": "将您的钢梁增益乘以",
    "My YouTube Channel": "我的 YouTube 频道",
    "Name": "姓名",
    "NBU Autobuyer:": "NBU自动购买者：",
    "NBUs and All RBU Levels,": "NBU 和所有 RBU 级别，",
    "Nerfed 3rd Golden Scrap upgrade effect.": "削弱了第 3 次金色废料升级效果。",
    "Nerfed 4th Golden Scrap upgrade cost.": "Nerfed 4th Golden Scrap 升级成本。",
    "New": "新的",
    "Next regenerator at": "下一个再生器在",
    "NMU Autobuyer:": "NMU自动购买者：",
    "NMUs and All RMU Levels,": "NMU 和所有 RMU 级别，",
    "No ✗": "没有✗",
    "Normal Brick Upgrades (NBU)": "普通砖升级 (NBU)",
    "Normal Magnet Upgrades (NMU)": "普通磁铁升级 (NMU)",
    "Notation :": "符号：",
    "Notation Improvement.": "符号改进。",
    "Notations now support negative numbers.": "符号现在支持负数。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);